#!/bin/bash

function composer {
  # Run Composer commands.
  php composer "${@}"
}

function drupal:install {
  # Install Drupal.
  cp --no-clobber .env.example .env

  . .env

  drush site:install -y \
    --account-pass="admin123" \
    --db-url="${DB_DRIVER}://${DB_USER}:${DB_PASSWORD}@${DB_HOST}/${DB_NAME}" \
    --site-name="Drupal Testing Workshop"

  touch .flag-built
}

function drush {
  # Run Drush commands.
  php drush "${@}"
}

function help {
  # Display the help text.
  printf "%s <task> [args]\n\nTasks:\n" "${0}"

  compgen -A function | grep -v "^_" | cat -n

  printf "\nExtended help:\n   Each task has comments for general usage.\n"
}

function lint:dockerfile {
  # Lint the Dockerfile using Hadolint.
  docker container run --rm -i \
    hadolint/hadolint hadolint \
      --ignore DL3008 \
      --ignore DL3022 \
      "${@}" - < tools/docker/Dockerfile
}

function php {
  # Run commands within the php container.
  docker-compose run --no-deps --rm php "${@}"
}

function shell {
  # Open a shell session in the php container.
  docker-compose exec php bash
}

function test {
  # Run PHPUnit tests.
  php phpunit "${@}"
}

TIMEFORMAT=$'\nTask completed in %3lR'
time ${@:-help}
